### ISSUE TITLE
Cascade Select not working

### ISSUE THREAD

**Issue by sakisdog** [open-admin-org/open-admin#110]
**Describe the bug**
Cascade select not working when trying to create new entry. The api returns the correct results but the select element shows nothing.

model code:
 ```
class Question extends Model
  {
      use SoftDeletes;
      
      public function category()
      {
          return $this->belongsTo(Category::class);
      }
      
      public function level()
      {
          return $this->belongsTo(Level::class);
      }
  }
```

api.php code
```
Route::post('/levels', function (Request $request) {
    $query = $request::input("query");
    // \Log::info(Level::where('category_id', $query)->get()->toArray());
    return Level::where('category_id', $query)->get(['id','number as text']);
    // return Level::where('category_id', $query)->get();
   
});

```
output from api:
```
[
    {
        "id": 2,
        "text": 1
    },
    {
        "id": 4,
        "text": 2
    },
    {
        "id": 6,
        "text": 3
    }
]
```

Controller code:
```
protected function form()
    {
        $form = new Form(new Question());

        $form->number('number', __('Number'));
        $form->text('question', __('Question'));
        $form->text('answer', __('Answer'));
        $form->image('image', __('Image'));
        $form->select('category_id')->options(Category::all()->pluck('name','id'))->load('level_id','/api/levels');
        $form->select('level_id');
        // $form->select('level_id')->options(Level::all()->pluck('number','id'));
        return $form;
    }
```

**System**
Open-admin version v1.0.27
PHP version | PHP/8.2.8
Laravel version | 10.30.1

**Comment by sakisdog** [comment]
Found the answer. It was in front of my eyes but was too tired to see it. Chrome's console log displayed the following error when i was selecting the category option:
```
An error has accurred:
open-admin.js:388 TypeError: s.localeCompare is not a function
    at t.sortByAlpha (choices.min.js:2:55342)
    at Array.sort (<anonymous>)
    at e._createChoicesFragment (choices.min.js:2:15266)
    at e._renderChoices (choices.min.js:2:13236)
    at e._render (choices.min.js:2:12676)
    at Object.g [as dispatch] (choices.min.js:2:85874)
    at e.dispatch (choices.min.js:2:60245)
    at e._stopLoading (choices.min.js:2:17918)
    at e.setChoices (choices.min.js:2:11923)
    at create:481:38
```
It seems that localeCompare does not work when the value is integer instead of string . The simple solution was to cast the integer as string before passing it to select element.
So the fix on the api.php is to replace:
```
return Level::where('category_id', $query)->get(['id','number as text']);
```
with
```
return Level::where('category_id', $query)->get(['id',DB::raw('CAST(number AS CHAR) AS text')]);
```
