### ISSUE TITLE
Custom Grid Tools - Batch Action Error

### ISSUE THREAD

**Issue by vincentchoo-intern** [open-admin-org/open-admin#172]
Hi, I tried using the code according to the documentation to create a custom batch action button, and also adjusting the input field accordingly to my database. Somehow, I've testing on my project and a new test project, the error persist when submitting the request to batch edit an input field (e.g. 'purpose'). Is there somewhere else that I missed in the documentation. 

i tried
1. creating a new project to test
2. works when create a batch edit to change a fixed value

![image](https://github.com/open-admin-org/open-admin/assets/162660347/ebce307c-27f7-4462-afd3-850a5115994b)

![image_7](https://github.com/open-admin-org/open-admin/assets/162660347/57868819-fb30-493b-a19a-64a3836f12ff)

![image](https://github.com/open-admin-org/open-admin/assets/162660347/4ef0208a-bf87-48a0-936a-c210931347b8)

![image](https://github.com/open-admin-org/open-admin/assets/162660347/2f2fb2a8-c6ec-4109-b42a-ee1f1763db3d)

This is the stacktrace from the Log Viewer, if it helps

```
[stacktrace]
#0 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Form\\Field.php(760): OpenAdmin\\Admin\\Form->model()
#1 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Form\\Field\\Traits\\HasValuePicker.php(61): OpenAdmin\\Admin\\Form\\Field->getRules()
#2 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Form\\Field.php(998): OpenAdmin\\Admin\\Form\\Field\\Textarea->getRules()
#3 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Actions\\Interactor\\Form.php(229): OpenAdmin\\Admin\\Form\\Field->getValidator()
#4 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Actions\\Action.php(319): OpenAdmin\\Admin\\Actions\\Interactor\\Form->validate()
#5 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Controllers\\HandleController.php(90): OpenAdmin\\Admin\\Actions\\Action->validate()
#6 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): OpenAdmin\\Admin\\Controllers\\HandleController->handleAction()
#7 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#8 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#10 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(806): Illuminate\\Routing\\Route->run()
#11 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\Permission.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\Permission->handle()
#14 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\Bootstrap.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\Bootstrap->handle()
#16 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\LogOperation.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\LogOperation->handle()
#18 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\Pjax.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\Pjax->handle()
#20 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\Throttle.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\Throttle->handle()
#22 C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Middleware\\Authenticate.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): OpenAdmin\\Admin\\Middleware\\Authenticate->handle()
#24 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#28 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#32 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#33 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#35 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#37 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#39 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#40 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(748): Illuminate\\Routing\\Router->runRoute()
#41 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#42 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#43 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#44 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#50 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#54 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#56 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#58 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#60 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 C:\\default\\jeep3\\jeep-track\\public\\index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 C:\\default\\jeep3\\jeep-track\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\resources\\server.php(16): require_once('...')
#63 {main}
"}

```

Thank you in advance. 

Edit:

Ok I found out how to fix this, apparently all the methods has to do is to just return any Model, it works even if I return an unrelated Model to the input field. 
`C:\\default\\jeep3\\jeep-track\\vendor\\open-admin-org\\open-admin\\src\\Form\\Field.php(760): OpenAdmin\\Admin\\Form->model()` 

```
public function model(): Model
    {
        if ($this->model instanceof InteractorForm) {

            //doesnt matter what type of Model
            return (new \App\Models\Admin());
        } else{
            return $this->model;
        } 
        
    }

```

**Comment by uluumbch** [comment]
@vincentchoo-intern how do you solve this? do you edit the open-admin file in vendor?

**Comment by vincentchoo-intern** [comment]
Hi, yes. You have to edit some lines in Form.php in the vendor. 

```
C:\default\jeep3\jeep-track\vendor\open-admin-org\open-admin\src\Form.php
```
```
public function model(): Model
    {
        if ($this->model instanceof InteractorForm) {

            //doesnt matter what type of Model
            return (new \App\Models\Admin());
        } else{
            return $this->model;
        } 
        
    }

```
I'm not sure if its the best solution but it works. Hope it helps.
